// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRqNcY2DUpdGHkX2EVsLu_LgkjY2eZA7o',
    appId: '1:991774707429:web:83d341008d103a70e34e0c',
    messagingSenderId: '991774707429',
    projectId: 'crud-firebase-6205e',
    authDomain: 'crud-firebase-6205e.firebaseapp.com',
    storageBucket: 'crud-firebase-6205e.appspot.com',
    measurementId: 'G-XC4HY1YTRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4gGkFVKhUuuPLHhw4uYt2HYj1bPASq0',
    appId: '1:991774707429:android:3234da944b301f0de34e0c',
    messagingSenderId: '991774707429',
    projectId: 'crud-firebase-6205e',
    storageBucket: 'crud-firebase-6205e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJr9XDi8PSw1bYwtKlGQ2YALPHXJ_yyg',
    appId: '1:991774707429:ios:033452fa16dbb317e34e0c',
    messagingSenderId: '991774707429',
    projectId: 'crud-firebase-6205e',
    storageBucket: 'crud-firebase-6205e.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJr9XDi8PSw1bYwtKlGQ2YALPHXJ_yyg',
    appId: '1:991774707429:ios:033452fa16dbb317e34e0c',
    messagingSenderId: '991774707429',
    projectId: 'crud-firebase-6205e',
    storageBucket: 'crud-firebase-6205e.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRqNcY2DUpdGHkX2EVsLu_LgkjY2eZA7o',
    appId: '1:991774707429:web:726415f05c3e4a58e34e0c',
    messagingSenderId: '991774707429',
    projectId: 'crud-firebase-6205e',
    authDomain: 'crud-firebase-6205e.firebaseapp.com',
    storageBucket: 'crud-firebase-6205e.appspot.com',
    measurementId: 'G-TV9CKN96E7',
  );

}